### ISSUE TITLE
ModuleNotFoundError: No module named 'config'

### ISSUE THREAD

**Issue by ghost** [cpease00/Spotify-Samples#2]
beautifulsoup4  4.9.3
pip             21.0.1
spotipy         2.17.1
Python 3.9.4
macOS 11.2

 `package % python3 ./sample_finder.py`
`Traceback (most recent call last):`
  `File "/Users/admin/Desktop/Spotify-Samples-master/data_science/spotify/package/./sample_finder.py", line 7, in <module>
    from config import *`
`ModuleNotFoundError: No module named 'config'`

config.py is missing

**Comment by ghost** [comment]
also, you may want to add `_chunk_size = 100` somewhere in there, spotify API doesn't allow for over 100 songs

**Comment by ghost** [comment]
Now I'm getting IndexError: list index out of range after removing the requirement for config.py and setting the spotify client id and client secret in the hard code.

`  File "/Users/admin/Desktop/Spotify-Samples-master/data_science/spotify/package/sample_finder.py", line 83, in <module>`
`    run_program()`
`  File "/Users/admin/Desktop/Spotify-Samples-master/data_science/spotify/package/sample_finder.py", line 79, in` `run_program`
`    playlist_id = uri.split(':')[4]`
`IndexError: list index out of range`

**Comment by ghost** [comment]
i dont know python, heres a config.py that does nothing i dont know what i was trying to do here
`import sys
config = {
	"Samples": {
		"Address": "localhost",
		"DB": "0",
		"Password": None,
		"Port": "8889"
	}
}
`

**Comment by ghost** [comment]
im sure this isn't for ppl who dont know python or anything, but I suggest adding to the README that config.py needs to be created by the user, the Spotify client ID and client secret need to be specified, spotify user URI/playlist URI (not sure abt this part, i prob did it wrong), bs4 and spotipy need to be installed using `pip install`, an app needs to be added on the spotify dev dashboard to get the client id + secret, the same redirect as the one in the sample_finder.py needs to be added in spotify app settings, etc

heres my file


[sample finder copy.py](https://github.com/cpease00/Spotify-Samples/files/6271256/sample.finder.copy.txt)
[config.py](https://github.com/cpease00/Spotify-Samples/files/6271260/config.copy.txt)

if only i knew what im doing

**Comment by ghost** [comment]
i got as far as
<img width="497" alt="SS 2021-04-07 at 4 44 12 AM" src="https://user-images.githubusercontent.com/41055950/113861305-e97c7d00-975b-11eb-9b23-95a4abcdd45e.png">
